module.exports = {
    "message":"accurate",
    "cod":"200",
    "count":15,
    "list":[
        {
            "id":4509177,
            "name":"Columbus",
            "coord":{
                "lon":-82.998787,
                "lat":39.961182
            },
            "main":{
                "temp":284.598,
                "temp_min":284.598,
                "temp_max":284.598,
                "pressure":975.25,
                "sea_level":1006.6,
                "grnd_level":975.25,
                "humidity":96
            },
            "dt":1456321701,
            "wind":{
                "speed":7.58,
                "deg":122.007
            },
            "sys":{
                "country":""
            },
            "rain":{  
                "3h":1.8925
            },
            "clouds":{  
                "all":64
            },
            "weather":[
                {  
                    "id":500,
                    "main":"Rain",
                    "description":"light rain",
                    "icon":"10d"
                }
            ]
        },
        {  
            "id":4512214,
            "name":"Franklin County",
            "coord":{  
                "lon":-83.016571,
                "lat":39.966728
            },
            "main":{  
                "temp":279,
                "pressure":994,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":280.15
            },
            "dt":1456322632,
            "wind":{  
                "speed":5.7,
                "deg":80
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":4506487,
            "name":"Bexley",
            "coord":{  
                "lon":-82.937683,
                "lat":39.968948
            },
            "main":{  
                "temp":284.598,
                "temp_min":284.598,
                "temp_max":284.598,
                "pressure":975.25,
                "sea_level":1006.6,
                "grnd_level":975.25,
                "humidity":96
            },
            "dt":1456322216,
            "wind":{  
                "speed":7.58,
                "deg":122.007
            },
            "sys":{  
                "country":""
            },
            "rain":{  
                "3h":1.8925
            },
            "clouds":{  
                "all":64
            },
            "weather":[  
                {  
                    "id":500,
                    "main":"Rain",
                    "description":"light rain",
                    "icon":"10d"
                }
            ]
        },
        {  
            "id":4513057,
            "name":"Grandview Heights",
            "coord":{  
                "lon":-83.040741,
                "lat":39.97979
            },
            "main":{  
                "temp":279.02,
                "pressure":996,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":280.15
            },
            "dt":1456321620,
            "wind":{  
                "speed":4.1,
                "deg":70
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":4526993,
            "name":"Upper Arlington",
            "coord":{  
                "lon":-83.062408,
                "lat":39.994511
            },
            "main":{  
                "temp":284.023,
                "temp_min":284.023,
                "temp_max":284.023,
                "pressure":970.95,
                "sea_level":1005.06,
                "grnd_level":970.95,
                "humidity":97
            },
            "dt":1456322216,
            "wind":{  
                "speed":8.28,
                "deg":116.007
            },
            "sys":{  
                "country":""
            },
            "rain":{  
                "3h":1.185
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":500,
                    "main":"Rain",
                    "description":"light rain",
                    "icon":"10d"
                }
            ]
        },
        {  
            "id":4528291,
            "name":"Whitehall",
            "coord":{  
                "lon":-82.88546,
                "lat":39.966728
            },
            "main":{  
                "temp":284.598,
                "temp_min":284.598,
                "temp_max":284.598,
                "pressure":975.25,
                "sea_level":1006.6,
                "grnd_level":975.25,
                "humidity":96
            },
            "dt":1456322216,
            "wind":{  
                "speed":7.58,
                "deg":122.007
            },
            "sys":{  
                "country":""
            },
            "rain":{  
                "3h":1.8925
            },
            "clouds":{  
                "all":64
            },
            "weather":[  
                {  
                    "id":500,
                    "main":"Rain",
                    "description":"light rain",
                    "icon":"10d"
                }
            ]
        },
        {  
            "id":5155393,
            "name":"Gahanna",
            "coord":{  
                "lon":-82.879341,
                "lat":40.01923
            },
            "main":{  
                "temp":278.77,
                "pressure":996,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":280.15
            },
            "dt":1456321922,
            "wind":{  
                "speed":4.1,
                "deg":70
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":5163149,
            "name":"Minerva Park",
            "coord":{  
                "lon":-82.943787,
                "lat":40.07645
            },
            "main":{  
                "temp":278.8,
                "pressure":996,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":280.15
            },
            "dt":1456322632,
            "wind":{  
                "speed":4.1,
                "deg":70
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":4520177,
            "name":"Obetz",
            "coord":{  
                "lon":-82.950737,
                "lat":39.878948
            },
            "main":{  
                "temp":279.34,
                "pressure":994,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":282.15
            },
            "dt":1456322632,
            "wind":{  
                "speed":5.7,
                "deg":80
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":5177396,
            "name":"Worthington",
            "coord":{  
                "lon":-83.01796,
                "lat":40.093121
            },
            "main":{  
                "temp":282.223,
                "temp_min":282.223,
                "temp_max":282.223,
                "pressure":970.3,
                "sea_level":1007.21,
                "grnd_level":970.3,
                "humidity":96
            },
            "dt":1456321702,
            "wind":{  
                "speed":8.68,
                "deg":106.007
            },
            "sys":{  
                "country":""
            },
            "rain":{  
                "3h":4.3075
            },
            "clouds":{  
                "all":92
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                }
            ]
        },
        {  
            "id":4516701,
            "name":"Lincoln Village",
            "coord":{  
                "lon":-83.130737,
                "lat":39.954788
            },
            "main":{  
                "temp":279.31,
                "pressure":996,
                "humidity":93,
                "temp_min":278.15,
                "temp_max":280.15
            },
            "dt":1456321620,
            "wind":{  
                "speed":4.1,
                "deg":70
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":5158156,
            "name":"Huber Ridge",
            "coord":{  
                "lon":-82.916573,
                "lat":40.088669
            },
            "main":{  
                "temp":278.78,
                "pressure":996,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":280.15
            },
            "dt":1456321922,
            "wind":{  
                "speed":4.1,
                "deg":70
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":5160938,
            "name":"Linworth",
            "coord":{  
                "lon":-83.049072,
                "lat":40.090061
            },
            "main":{  
                "temp":278.78,
                "pressure":996,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":280.15
            },
            "dt":1456321922,
            "wind":{  
                "speed":4.1,
                "deg":70
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":4506666,
            "name":"Blacklick Estates",
            "coord":{  
                "lon":-82.864342,
                "lat":39.90506
            },
            "main":{  
                "temp":279.35,
                "pressure":994,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":282.15
            },
            "dt":1456322632,
            "wind":{  
                "speed":5.7,
                "deg":80
            },
            "sys":{  
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[  
                {  
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {  
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        },
        {  
            "id":4513425,
            "name":"Groveport",
            "coord":{
                "lon":-82.883789,
                "lat":39.878399
            },
            "main":{
                "temp":279.34,
                "pressure":994,
                "humidity":93,
                "temp_min":277.15,
                "temp_max":282.15
            },
            "dt":1456322632,
            "wind":{
                "speed":5.7,
                "deg":80
            },
            "sys":{
                "country":""
            },
            "clouds":{  
                "all":90
            },
            "weather":[
                {
                    "id":501,
                    "main":"Rain",
                    "description":"moderate rain",
                    "icon":"10d"
                },
                {
                    "id":701,
                    "main":"Mist",
                    "description":"mist",
                    "icon":"50d"
                }
            ]
        }
    ]
};